version: '3.0'
services:
  laravel:
    container_name: laravel
    ports:
     - 9000:9000
    build: .
    networks:
      - laranet
  nginx:
    container_name: nginx
    ports:
      - 80:80
    build: ./nginx
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
